### ISSUE TITLE
About the compilation of bruteforce-erldp.c

### ISSUE THREAD

**Issue by kikulo** [gteissier/erl-matter#1]
Hi, I tried to compile bruteforce-erldp into a linux executable file but encountered an error.
Can you give me some suggestions？

#root gcc bruteforce-erldp.c -o bruteforce-erldp
/usr/bin/ld: /tmp/ccwCtYAc.o: in function `create_interval':
bruteforce-erldp.c:(.text+0x9d): undefined reference to `pthread_barrier_init'
/usr/bin/ld: /tmp/ccwCtYAc.o: in function `worker_run':
bruteforce-erldp.c:(.text+0x671): undefined reference to `create_cookie'
/usr/bin/ld: bruteforce-erldp.c:(.text+0xa17): undefined reference to `compute_response'
/usr/bin/ld: bruteforce-erldp.c:(.text+0xb76): undefined reference to `pthread_barrier_wait'
/usr/bin/ld: /tmp/ccwCtYAc.o: in function `main':
bruteforce-erldp.c:(.text+0x13bd): undefined reference to `jsmn_init'
/usr/bin/ld: bruteforce-erldp.c:(.text+0x13e4): undefined reference to `jsmn_parse'
/usr/bin/ld: bruteforce-erldp.c:(.text+0x1a77): undefined reference to `pthread_create'
/usr/bin/ld: bruteforce-erldp.c:(.text+0x1d42): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

**Comment by gteissier** [comment]
Hi,

The program you try to compile by hand is based on pthread, and it will use nettle cryptographic implementations.

So basically you have two options:
1. Use the proposed building scheme based on Make: ensure you have nettle library and its headers, and type make. If you just need bruteforce-erldp, type make bruteforce-erldp
2. Build your own builiding scheme: ensure path to nettle headers is included, compile using -pthread, and link to nettle library.

OFC, the 1 above is the preferred way to build it.
