### ISSUE TITLE
commands not found with bruteforce

### ISSUE THREAD

**Issue by bhanna98** [gteissier/erl-matter#5]
./bruteforce-erldp.c: line 24: static: command not found
./bruteforce-erldp.c: line 25: static: command not found
./bruteforce-erldp.c: line 26: static: command not found
./bruteforce-erldp.c: line 27: static: command not found
./bruteforce-erldp.c: line 28: static: command not found
./bruteforce-erldp.c: line 29: static: command not found
./bruteforce-erldp.c: line 36: struct: command not found
./bruteforce-erldp.c: line 37: uint64_t: command not found
./bruteforce-erldp.c: line 38: uint64_t: command not found
./bruteforce-erldp.c: line 39: float: command not found
./bruteforce-erldp.c: line 40: unsigned: command not found
./bruteforce-erldp.c: line 41: pthread_barrier_t: command not found
./bruteforce-erldp.c: line 42: syntax error near unexpected token `interval'
./bruteforce-erldp.c: line 42: `  TAILQ_ENTRY(interval) _next;'

**Comment by gteissier** [comment]
hi bhanna98,
this file is a C file, it is not meant to be executed the way you try to use it, but rather compiled and later linked to produce a binary that should be executed.
